### ISSUE TITLE
Navbar Temp not showing on raspberry pi 3b+

### ISSUE THREAD

**Issue by Jonijakob** [imrahil/OctoPrint-NavbarTemp#81]
hi I am trying to check the SoC temperature on the raspberry pi 3b+ and it didn't show it
Maybe because the Broadcom is BCM2837B0?

**Comment by bepstein111** [comment]
Same here. Using `/opt/vc/bin/vcgencmd measure_temp` as the command works fine but adds an ugly temp= before the number. I'm not great with awk, but I think the following command is correct as it works in terminal, but not in Navbar: `/opt/vc/bin/vcgencmd measure_temp | awk -F= '{printf("%d%s\n", $2,  "°C")}'`
Not sure why I have to add the "°C" back in, but as I said, it works in terminal on the pi over ssh, but not when used as a command with this plugin.

BTW I'm using a Pi 4 4GB

**Comment by rknobbe** [comment]
Same here with Raspberry Pi 4

**Comment by robertomilan** [comment]
Rasperry Pi 4 1GB on OctoPrint 1.4.1/1.4.2, SoC not shown here too.

**Comment by Anubisbe** [comment]
same problem no more Soc temp after 1.4.2 release of octoprint and update of raspberry (Raps pi 4B) python2.7
try the fix ""if sys.platform.startswith("linux"):"" but no change

**Comment by DodgeDeBoulet** [comment]
I did a little digging in the source and believe I have located the issue. I've fixed it in my local installation and it appears to work for the Raspberry Pi 4.

Line 17 of ~/oprint/lib/python2.7/site-packages/octoprint_navbartemp/libs/sbc.py is:

```
    piSocTypes = (["BCM2708", "BCM2709", "BCM2835"])
```
And should be changed to:

```
    piSocTypes = (["BCM2708", "BCM2709", "BCM2835", "BCM2711"])
```
Line 104 is:
```
         self.temp_cmd = '/opt/vc/bin/vcgencmd measure_temp'
```
And **may** need to be changed to:

```
         self.temp_cmd = '/usr/bin/vcgencmd measure_temp'
```
The reason I say "may" is that vcgencmd exists in both locations and appears to produce the same output. I read another post on a related issue that indicated that the path may need to be updated, because changing it for that user fixed his/her issue.

**Comment by ChaosBlades** [comment]
Works for me on Pi4 and OctoPi 0.17.0

I only needed to add the new piSocType.

**Comment by robertomilan** [comment]
Works on Pi4 1GB OctoPi 0.17.0. Added piSocType only.

**Comment by domhardt** [comment]
Same problem here. Raspberry Pi 3B+, OctoPrint 1.4.2 running on OctoPi image, Navbar Temperature Plugin 0.14, Python 3

**Comment by rippiedoos** [comment]
My best guess is around line 40, as mentioned in #78
https://github.com/imrahil/OctoPrint-NavbarTemp/blob/0efd791a590b27b4ca281422be8395e6d1ff85a7/octoprint_navbartemp/__init__.py#L40

If you're running Python3, the SBC-code never get's called because of the undetected platform. I changed that line to:
```
if sys.platform.startswith('linux'):
```
And the SoC-temp get's displayed again.

**Comment by LazeMSS** [comment]
This is fixed in the current released version and should be closed :)
